// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Groups      string
	Invitations string
	Schedules   string
	UserGroup   string
	Users       string
}{
	Groups:      "groups",
	Invitations: "invitations",
	Schedules:   "schedules",
	UserGroup:   "user_group",
	Users:       "users",
}
