version: '3.8'

volumes:
  db-store:

services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: infra/docker/server/Dockerfile.dev
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./server
        target: /server
  db:
    container_name: db
    build:
      context: .
      dockerfile: infra/docker/db/Dockerfile.dev
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: sharely
      MYSQL_USER: sharely
      MYSQL_PASSWORD: testtest
      TZ: 'Asia/Tokyo'
