version: '3.8'

volumes:
  db-store:

services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: ../infra/docker/client/Dockerfile.dev
    volumes:
      - type: bind
        source: ./client
        target: /client
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: ../infra/docker/server/Dockerfile.dev
    volumes:
      - type: bind
        source: ./server
        target: /server
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      DB_USER: sharely
      DB_PASS: testtest
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: sharely
  db:
    container_name: db
    build:
      context: ./infra/docker/db
      dockerfile: Dockerfile.dev
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: sharely
      MYSQL_USER: sharely
      MYSQL_PASSWORD: testtest
