version: '3.8'
services:
  server:
    build: 
      context: .
      dockerfile: infra/docker/server/Dockerfile.dev
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./server
        target: /server
