@startuml

entity "users" as users {
    + id : int [PK]
    --
    sex : int
    name : varchar
    email : varchar
    password : varchar
    image : varchar
    created_at : datetime
    updated_at : datetime
}

entity "groups" as groups {
    + id : int [PK]
    --
    name : varchar
    creator_id : int [FK]
    created_at : datetime
    updated_at : datetime
}

entity "user_group" as user_group {
    + user_id : int [PK]
    + group_id : int [PK]
    --
    created_at : datetime
    updated_at : datetime
}

entity "schedules" as schedules {
    + id : int [PK]
    --
    title : varchar
    description : text
    start_datetime : datetime
    end_datetime : datetime
    is_repeated : boolean
    color : int
    user_group_id : int [FK]
    created_at : datetime
    updated_at : datetime
}

entity "invitations" as invitations {
    + id : int [PK]
    --
    sender_id : int [FK]
    receiver_id : int [FK]
    group_id : int [FK]
    created_at : datetime
    updated_at : datetime
}

users ||--o{ user_group
groups ||--o{ user_group
user_group ||--o{ schedules
users ||--o{ groups : creator
users ||--o{ invitations : sender
users ||--o{ invitations : receiver
groups ||--o{ invitations

@enduml
