FROM node:20-slim

RUN adduser --disabled-password --gecos '' nonroot

WORKDIR /client

RUN chown -R nonroot:nonroot /client

COPY package* ./
COPY yarn.lock ./
RUN yarn

COPY . .

USER nonroot
CMD ["yarn", "dev"]
