FROM golang:1.20.5-alpine AS build

WORKDIR /server

COPY server/go.mod ./
COPY server/go.sum ./
RUN go mod download

COPY server/ .

RUN go install github.com/cosmtrek/air@latest

CMD ["air", "-c", ".air.toml"]
