FROM golang:1.20.5-alpine AS build

WORKDIR /server

COPY server/go.mod server/go.sum ./
RUN go mod download

RUN go install github.com/cosmtrek/air@latest && \
    go install github.com/pressly/goose/cmd/goose

COPY server/ .

CMD ["air", "-c", ".air.toml"]
