# ビルドステージ
FROM golang:1.21-alpine AS build

WORKDIR /server

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./app/main.go

# 実行ステージ
FROM gcr.io/distroless/base-debian12

WORKDIR /

COPY --from=build /server/main /app/main

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/app/main"]
