name: Docker Security Scan

on:
  push:
    paths:
      - "infra/docker/**"

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t client -f infra/docker/client/Dockerfile.dev .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "client:latest"
          format: "table"
          exit-code: "1"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run Dockle on Client
        uses: goodwithtech/dockle-action@main
        with:
          image: "client:latest"
          format: "table"
          exit-code: "1"
          exit-level: "CRITICAL,HIGH"
          ignore: "CIS-DI-0010"
