name: Deploy to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - stg
      - feature/change-ecs-x64-to-arm

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS OIDC authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ap-northeast-1

      - name: login ECR repository
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "sharely-stg-frontend"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/client/Dockerfile.stg -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./client
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition sharely-stg-frontend-task-definition \
          --query taskDefinition > ecs-task-definition.json

      - name: Update task-definition parameters
        run: >
          cat ecs-task-definition.json | jq '.containerDefinitions=[.containerDefinitions[] |
            select(.name=="sharely-stg-frontend-container").image="${{ steps.build-image.outputs.image }}"
          ] |
          del (.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities) |
          .cpu="256" |
          .memory="512"' > task-definition.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          task-definition: task-definition.json
          service: frontend-service
          cluster: sharely-stg-cluster
          wait-for-service-stability: true
