name: CI for Client

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - client/app/**
  workflow_dispatch:

jobs:
  run-ci-for-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker version

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 19

      - name: Docker Compose Build and Up
        run: |
          docker compose build client
          docker compose run client yarn
          docker compose up -d client

      - name: Docker Compose Process
        run: docker compose ps -a

      - name: Next Format
        run: docker compose exec -T client yarn lint
