name: Docker Security Scan

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "infra/docker/client/Dockerfile.dev"
  workflow_dispatch:

jobs:
  scan-client-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image using Buildx
        run: |
          docker buildx create --use
          docker buildx build --load -t client:scan -f infra/docker/client/Dockerfile.dev client/.

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "client:scan"
          format: "table"
          exit-code: "1"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run Dockle on Client
        uses: goodwithtech/dockle-action@main
        with:
          image: "client:scan"
          format: "json"
          exit-code: "1"
          exit-level: "warn"
          ignore: "CIS-DI-0010"
          accept-key: "savedAptMark"
